version: '3'
services:
  webserver:
    build: ./
    tty: true
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    ports:
      - '80:3000'
    environment:
      ETH_ADDRESS: ${ETH_ADDRESS}
      STARK_PUBLIC_KEY: ${STARK_PUBLIC_KEY}
      STARK_PRIVATE_KEY: ${STARK_PRIVATE_KEY}
      API_KEY: ${API_KEY}
      API_PASSPHRASE: ${API_PASSPHRASE}
      API_SECRET: ${API_SECRET}
      TRADINGVIEW_PASSPHRASE: ${TRADINGVIEW_PASSPHRASE}
      SENTRY_DNS: ${SENTRY_DNS}
      PERPETUAL_PRIVATE_KEY: ${PERPETUAL_PRIVATE_KEY}
      PERPETUAL_REFERRAL_CODE: ${PERPETUAL_REFERRAL_CODE}
      ETH_ADDRESS1: ${ETH_ADDRESS1}
      STARK_PUBLIC_KEY1: ${STARK_PUBLIC_KEY1}
      STARK_PRIVATE_KEY1: ${STARK_PRIVATE_KEY1}
      API_KEY1: ${API_KEY1}
      API_PASSPHRASE1: ${API_PASSPHRASE1}
      API_SECRET1: ${API_SECRET1}
      TRADINGVIEW_PASSPHRASE1: ${TRADINGVIEW_PASSPHRASE1}
      ETH_ADDRESS2: ${ETH_ADDRESS2}
      STARK_PUBLIC_KEY2: ${STARK_PUBLIC_KEY2}
      STARK_PRIVATE_KEY2: ${STARK_PRIVATE_KEY2}
      API_KEY2: ${API_KEY2}
      API_PASSPHRASE2: ${API_PASSPHRASE2}
      API_SECRET2: ${API_SECRET2}
      TRADINGVIEW_PASSPHRASE2: ${TRADINGVIEW_PASSPHRASE2}
      ETH_ADDRESS3: ${ETH_ADDRESS3}
      STARK_PUBLIC_KEY3: ${STARK_PUBLIC_KEY3}
      STARK_PRIVATE_KEY3: ${STARK_PRIVATE_KEY3}
      API_KEY3: ${API_KEY3}
      API_PASSPHRASE3: ${API_PASSPHRASE3}
      API_SECRET3: ${API_SECRET3}
      TRADINGVIEW_PASSPHRASE3: ${TRADINGVIEW_PASSPHRASE3}
      ETH_ADDRESS4: ${ETH_ADDRESS4}
      STARK_PUBLIC_KEY4: ${STARK_PUBLIC_KEY4}
      STARK_PRIVATE_KEY4: ${STARK_PRIVATE_KEY4}
      API_KEY4: ${API_KEY4}
      API_PASSPHRASE4: ${API_PASSPHRASE4}
      API_SECRET4: ${API_SECRET4}
      TRADINGVIEW_PASSPHRASE4: ${TRADINGVIEW_PASSPHRASE4}
      ETH_ADDRESS5: ${ETH_ADDRESS5}
      STARK_PUBLIC_KEY5: ${STARK_PUBLIC_KEY5}
      STARK_PRIVATE_KEY5: ${STARK_PRIVATE_KEY5}
      API_KEY5: ${API_KEY5}
      API_PASSPHRASE5: ${API_PASSPHRASE5}
      API_SECRET5: ${API_SECRET5}
      TRADINGVIEW_PASSPHRASE5: ${TRADINGVIEW_PASSPHRASE5}
      ETH_ADDRESS6: ${ETH_ADDRESS6}
      STARK_PUBLIC_KEY6: ${STARK_PUBLIC_KEY6}
      STARK_PRIVATE_KEY6: ${STARK_PRIVATE_KEY6}
      API_KEY6: ${API_KEY6}
      API_PASSPHRASE6: ${API_PASSPHRASE6}
      API_SECRET6: ${API_SECRET6}
      TRADINGVIEW_PASSPHRASE6: ${TRADINGVIEW_PASSPHRASE6}
      SENTRY_DNS: ${SENTRY_DNS}
      PERPETUAL_PRIVATE_KEY: ${PERPETUAL_PRIVATE_KEY}
      PERPETUAL_REFERRAL_CODE: ${PERPETUAL_REFERRAL_CODE}
    command: yarn start:dev
